export const questions = [
  {
    id: "weight",
    question: "What is your current weight?",
    inputType: "number",
    placeholder: "Enter weight in lbs",
  },
  {
    id: "targetWeight",
    question: "What is your target weight?",
    inputType: "number",
    placeholder: "Enter target weight in lbs",
  },
  {
    id: "height",
    question: "What is your height?",
    inputType: "number",
    placeholder: "Enter height in inches",
  },
  {
    id: "age",
    question: "What is your age?",
    inputType: "number",
    placeholder: "Enter your age",
  },
  {
    id: "activityLevel",
    question: "What is your activity level?",
    inputType: "select",
    placeholder: "Select activity level",
    options: [
      { value: "SEDENTARY", label: "Sedentary (little to no exercise)" },
      { value: "LIGHT", label: "Light (light exercise 1-3 days/week)" },
      {
        value: "MODERATE",
        label: "Moderate (moderate exercise 3-5 days/week)",
      },
      { value: "VERY", label: "Very Active (hard exercise 6-7 days/week)" },
      {
        value: "SUPER",
        label: "Super Active (very hard exercise & physical job)",
      },
    ],
  },
  {
    id: "gender",
    question: "What is your gender?",
    inputType: "select",
    placeholder: "Select gender",
    options: [
      { value: "MALE", label: "Male" },
      { value: "FEMALE", label: "Female" },
    ],
  },
  {
    id: "dietaryRestrictions",
    question: "Do you have any dietary restrictions?",
    inputType: "multiselect",
    placeholder: "Select all that apply",
    options: [
      { value: "PEANUTS", label: "Peanuts" },
      { value: "TREENUTS", label: "Tree Nuts" },
      { value: "FISH", label: "Fish" },
      { value: "SHELLFISH", label: "Shellfish" },
      { value: "SOY", label: "Soy" },
      { value: "EGG", label: "Eggs" },
      { value: "WHEAT", label: "Wheat" },
      { value: "DAIRY", label: "Dairy" },
      { value: "SESAME", label: "Sesame" },
      { value: "MUSTARD", label: "Mustard" },
      { value: "GLUTEN", label: "Gluten" },
      { value: "ALCOHOL", label: "Alcohol" },
      { value: "BEEF", label: "Beef" },
      { value: "PORK", label: "Pork" },
      { value: "NONE", label: "None" },
    ],
  },
  {
    id: "healthConditions",
    question: "Do you have any health conditions?",
    inputType: "multiselect",
    placeholder: "Select all that apply",
    options: [
      { value: "IBS", label: "IBS" },
      { value: "DIABETES", label: "Diabetes" },
      { value: "HBP", label: "High Blood Pressure" },
      { value: "CANCER", label: "Cancer" },
      { value: "OBESITY", label: "Obesity" },
      { value: "KIDNEY_DISEASE", label: "Kidney Disease" },
      { value: "HEART_DISEASE", label: "Heart Disease" },
      { value: "NONE", label: "None" },
    ],
  },
  {
    id: "activeDiet",
    question: "What diet do you follow?",
    inputType: "select",
    placeholder: "Select diet",
    options: [
      { value: "MEDITERRANEAN", label: "Mediterranean" },
      { value: "KETO", label: "Keto" },
      { value: "PALEO", label: "Paleo" },
      { value: "VEGAN", label: "Vegan" },
      { value: "CARNIVORE", label: "Carnivore" },
      { value: "ATKINS", label: "Atkins" },
      { value: "NONE", label: "None" },
    ],
  },
] as const;

export type QuestionId = (typeof questions)[number]["id"];
